baseURL = "https://andre.cool/"
languageCode = "en-us"
title = "Hello, World!"

pygmentsCodeFences = true
pygmentsOptions = "style=manni,noclasses=true,linenos=sure"

[permalinks]
  posts = "/:year/:month/:slug/"

[author]
  name = "Andr√© Medeiros"

[params]
  githubRepo = "https://github.com/andremedeiros/andre.cool"
